[build]
  command = "npm run build"
  publish = "out"

[build.environment]
  NEXT_PUBLIC_BACKEND_URL = "https://alphastar-alb-2018657447.us-east-1.elb.amazonaws.com"
  NEXT_PUBLIC_WS_URL = "wss://alphastar-alb-2018657447.us-east-1.elb.amazonaws.com"
  NODE_VERSION = "18"
  NPM_FLAGS = "--prefix=/dev/null"
